/**
 * board_config.h — hardware definitions for the Waveshare
 * RP2350-Touch-LCD-3.49
 *
 * THE SINGLE SOURCE OF TRUTH. Every pin number here was read directly off
 * Waveshare's official schematic (RP2350-Touch-LCD-3.49.pdf); none of it is
 * guessed. Any hardware-related number is taken from here rather than being
 * embedded in the code.
 *
 * MCU : RP2350B (2x Cortex-M33 @ 150 MHz, FPU + DSP)
 * RAM : 520 KB SRAM — NO PSRAM
 * ROM : 16 MB QSPI flash (PY25Q128HA)
 */
#ifndef POKEBIRD_BOARD_CONFIG_H
#define POKEBIRD_BOARD_CONFIG_H

/* ── Audio: ES8311 codec + analog MEMS mic (MIC1) + NS4150B class-D amp ── */
#define PB_PIN_NS_MODE      0   /* NS4150B speaker amp mode/enable             */
#define PB_PIN_I2S_DSDIN    1   /* MCU  -> codec DAC  (playback)               */
#define PB_PIN_I2S_DSOUT    2   /* codec ADC -> MCU   (MICROPHONE DATA)        */
#define PB_PIN_I2S_MCLK     3   /* generated by PIO; the ES8311 derives from it */
#define PB_PIN_I2S_SCLK     4   /* BCLK — the ES8311 generates it as master    */
#define PB_PIN_I2S_LRCK     5   /* WS   — the ES8311 generates it as master    */

/* ── Shared I2C (codec control). The IMU and RTC are on it but unused ──── */
#define PB_PIN_I2C_SDA      6
#define PB_PIN_I2C_SCL      7
#define PB_I2C_INST         i2c1        /* GPIO6/7 -> I2C1                     */
#define PB_I2C_BAUD         400000

/* Peripherals deliberately left unused:
 *   GPIO8/9  IMU_INT1/2 — QMI8658: contributes nothing to this project
 *   GPIO10   RTC_INT    — PCF85063: no battery backup, so it loses the time
 * The pins are documented here so they are not used by accident later. */
#define PB_PIN_IMU_INT1     8   /* UNUSED */
#define PB_PIN_IMU_INT2     9   /* UNUSED */
#define PB_PIN_RTC_INT      10  /* UNUSED */

/* ── Touch: AXS15231B, the same chip as the LCD but a SEPARATE I2C bus ── */
#define PB_PIN_TP_INT       11
#define PB_PIN_TP_SDA       32
#define PB_PIN_TP_SCL       33
#define PB_TP_I2C_INST      i2c0        /* GPIO32/33 -> I2C0                   */
#define PB_TP_I2C_BAUD      400000
#define PB_TP_I2C_ADDR      0x3B        /* AXS15231B touch address             */

/* ── Free GPIOs: the P3 header (12-19) and the J3/J6 header (41-47) ──
 * These are where an external I2S MEMS microphone would go, if one is ever
 * needed. */
#define PB_PIN_FREE_HDR_P3_FIRST   12
#define PB_PIN_FREE_HDR_P3_LAST    19
#define PB_PIN_FREE_HDR_J3_FIRST   41
#define PB_PIN_FREE_HDR_J3_LAST    47

/* ── Display: AXS15231B, 172x640 IPS, QSPI ── */
#define PB_PIN_LCD_SCL      20
#define PB_PIN_LCD_D0       21
#define PB_PIN_LCD_D1       22
#define PB_PIN_LCD_D2       23
#define PB_PIN_LCD_D3       24
#define PB_PIN_LCD_CS       25
#define PB_PIN_LCD_RST      34
#define PB_PIN_LCD_TE       35      /* tearing effect — to avoid tearing        */
#define PB_PIN_LCD_BL       36      /* backlight PWM                            */
#define PB_PIN_BL_EN        37      /* backlight boost converter enable        */

#define PB_LCD_NATIVE_W     172
#define PB_LCD_NATIVE_H     640
/* The device is held in landscape: a 640x172 strip */
#define PB_LCD_W            640
#define PB_LCD_H            172

/* ── SD card (SPI mode; SD_D1/D2 are present, 4-bit SDIO is possible later) ── */
#define PB_PIN_SD_SCLK      26
#define PB_PIN_SD_MOSI      27
#define PB_PIN_SD_MISO      28
#define PB_PIN_SD_D1        29
#define PB_PIN_SD_D2        30
#define PB_PIN_SD_CS        31

/* ── Power ── */
#define PB_PIN_SYS_OUT      38      /* power latch: state                      */
#define PB_PIN_SYS_EN       39      /* power latch: used to switch itself off  */
#define PB_PIN_BAT_ADC      40      /* battery voltage (ADC)                   */
#define PB_BAT_ADC_CHANNEL  (PB_PIN_BAT_ADC - 40)   /* RP2350B: ADC0 = GPIO40  */
/* The divider on the schematic: R15 100K / R3 200K -> Vbat = Vadc * 1.5 */
#define PB_BAT_DIVIDER      1.5f

/* ── Audio pipeline parameters ──
 * 24 kHz was chosen for its 12 kHz Nyquist, which covers species that sing at
 * 7-9 kHz (wrens and treecreepers, for instance). 16 kHz would have clipped
 * them. */
#define PB_SAMPLE_RATE      24000
#define PB_MCLK_RATE        (PB_SAMPLE_RATE * 256)
#define PB_BITS_PER_SAMPLE  16
#define PB_MIC_GAIN         3       /* ES8311 PGA step */

#endif /* POKEBIRD_BOARD_CONFIG_H */
