/* GENERATED FILE — tools/sinif_tablosu.py. DO NOT EDIT BY HAND.
 * Source: data/egitim/siniflar.csv (179 classes)
 *
 * Class 178 = negative / unknown.
 * The arrays live in flash (const), so they cost no RAM.
 */
#ifndef POKEBIRD_SINIFLAR_H
#define POKEBIRD_SINIFLAR_H

#define PB_SINIF_SAYISI 179

static const char *const pb_sinif_kod[PB_SINIF_SAYISI] = {
  "alepar2",
  "alpswi1",
  "barswa",
  "bcnher",
  "bearee1",
  "bkbplo",
  "bkhgul",
  "bkwsti",
  "blackc1",
  "blakit1",
  "blared1",
  "blueth",
  "blutit",
  "booeag1",
  "brambl",
  "callar1",
  "casgul2",
  "cetwar1",
  "cirbun1",
  "coatit2",
  "colfly1",
  "combuz1",
  "comcha",
  "comchi1",
  "comcra",
  "comcuc",
  "comgre",
  "comhom1",
  "comkin1",
  "commoo3",
  "comnig1",
  "compoc",
  "comqua1",
  "comrav",
  "comred1",
  "comred2",
  "comros",
  "comsan",
  "comsni",
  "comswi",
  "comter",
  "corbun1",
  "corplo",
  "cowpig1",
  "crelar1",
  "dunlin",
  "dunnoc1",
  "eaowar1",
  "eargre",
  "eaywag1",
  "eubeat1",
  "eucdov",
  "eugori2",
  "eugplo",
  "eugwoo2",
  "euhbuz1",
  "euhgul1",
  "eupfly1",
  "euptit1",
  "eurbla",
  "eurcoo",
  "eurcur",
  "eurgol",
  "eurgre1",
  "eurhob",
  "eurjac",
  "eurjay1",
  "eurkes",
  "eurlin1",
  "eurmag1",
  "eurnig1",
  "eurnut2",
  "euroys1",
  "eurrob1",
  "eursco1",
  "eurser1",
  "eursis",
  "eurspa1",
  "eursta",
  "eurwar1",
  "eurwoo",
  "eurwry",
  "eutdov",
  "eutspa",
  "fieldf",
  "firecr1",
  "gadwal",
  "gargan",
  "garwar1",
  "gnwtea",
  "goldcr1",
  "gragoo",
  "graher1",
  "grcgre1",
  "grebit1",
  "grecor",
  "greegr",
  "grefla3",
  "gretit1",
  "grnsan",
  "grrwar1",
  "grswoo",
  "grywag",
  "gwfgoo",
  "gyfwoo1",
  "hawfin",
  "hoocro1",
  "hoopoe",
  "houspa",
  "humwar1",
  "ictwar1",
  "leswoo1",
  "litegr",
  "litgre1",
  "litowl1",
  "litter1",
  "loeowl",
  "lottit1",
  "mallar3",
  "martit2",
  "marwar3",
  "meapip1",
  "medgul1",
  "mewgul",
  "misthr1",
  "miswoo1",
  "mutswa",
  "norhar1",
  "norlap",
  "norwhe",
  "ortbun1",
  "palswi3",
  "perfal",
  "purher1",
  "rebfly",
  "rebshr1",
  "redcro",
  "redwin",
  "reebun",
  "retpip",
  "rinouz1",
  "rocpig",
  "rook1",
  "rudtur",
  "santer1",
  "sarwar1",
  "savwar1",
  "sedwar1",
  "shteag1",
  "shttre1",
  "skylar",
  "sonthr1",
  "spaspa1",
  "spocra1",
  "spofly1",
  "squher1",
  "stonec4",
  "syrwoo1",
  "tawowl1",
  "tawpip1",
  "thrnig1",
  "trepip",
  "tufduc",
  "watpip1",
  "watrai1",
  "webowl1",
  "wemhar1",
  "whimbr5",
  "whinch1",
  "whisto1",
  "whiwag",
  "whoswa",
  "winwre4",
  "wlwwar",
  "woolar1",
  "woosan",
  "yelgul1",
  "yellow2",
  "__negatif__",
};

static const char *const pb_sinif_ad[PB_SINIF_SAYISI] = {
  "Alexandrine Parakeet",
  "Alpine Swift",
  "Barn Swallow",
  "Black-crowned Night Heron",
  "Bearded Reedling",
  "Black-bellied Plover",
  "Black-headed Gull",
  "Black-winged Stilt",
  "Eurasian Blackcap",
  "Black Kite",
  "Black Redstart",
  "Bluethroat",
  "Eurasian Blue Tit",
  "Booted Eagle",
  "Brambling",
  "Calandra Lark",
  "Caspian Gull",
  "Cetti's Warbler",
  "Cirl Bunting",
  "Coal Tit",
  "Collared Flycatcher",
  "Common Buzzard",
  "Common Chaffinch",
  "Common Chiffchaff",
  "Common Crane",
  "Common Cuckoo",
  "Common Greenshank",
  "Western House-Martin",
  "Common Kingfisher",
  "Eurasian Moorhen",
  "Common Nightingale",
  "Common Pochard",
  "Common Quail",
  "Common Raven",
  "Common Redshank",
  "Common Redstart",
  "Common Rosefinch",
  "Common Sandpiper",
  "Common Snipe",
  "Common Swift",
  "Common Tern",
  "Corn Bunting",
  "Common Ringed Plover",
  "Common Wood-Pigeon",
  "Crested Lark",
  "Dunlin",
  "Dunnock",
  "Eastern Olivaceous Warbler",
  "Eared Grebe",
  "Western Yellow Wagtail",
  "European Bee-eater",
  "Eurasian Collared-Dove",
  "Eurasian Golden Oriole",
  "European Golden-Plover",
  "Eurasian Green Woodpecker",
  "European Honey-buzzard",
  "European Herring Gull",
  "European Pied Flycatcher",
  "Eurasian Penduline-Tit",
  "Eurasian Blackbird",
  "Eurasian Coot",
  "Eurasian Curlew",
  "European Goldfinch",
  "European Greenfinch",
  "Eurasian Hobby",
  "Eurasian Jackdaw",
  "Eurasian Jay",
  "Eurasian Kestrel",
  "Eurasian Linnet",
  "Eurasian Magpie",
  "Eurasian Nightjar",
  "Eurasian Nuthatch",
  "Eurasian Oystercatcher",
  "European Robin",
  "Eurasian Scops-Owl",
  "European Serin",
  "Eurasian Siskin",
  "Eurasian Sparrowhawk",
  "European Starling",
  "Common Reed Warbler",
  "Eurasian Woodcock",
  "Eurasian Wryneck",
  "European Turtle-Dove",
  "Eurasian Tree Sparrow",
  "Fieldfare",
  "Common Firecrest",
  "Gadwall",
  "Garganey",
  "Garden Warbler",
  "Green-winged Teal",
  "Goldcrest",
  "Graylag Goose",
  "Gray Heron",
  "Great Crested Grebe",
  "Eurasian Bittern",
  "Great Cormorant",
  "Great Egret",
  "Greater Flamingo",
  "Great Tit",
  "Green Sandpiper",
  "Great Reed Warbler",
  "Great Spotted Woodpecker",
  "Gray Wagtail",
  "Greater White-fronted Goose",
  "Gray-headed Woodpecker",
  "Hawfinch",
  "Hooded Crow",
  "Common Hoopoe",
  "House Sparrow",
  "Hume's Warbler",
  "Icterine Warbler",
  "Lesser Spotted Woodpecker",
  "Little Egret",
  "Little Grebe",
  "Little Owl",
  "Little Tern",
  "Long-eared Owl",
  "Long-tailed Tit",
  "Mallard",
  "Marsh Tit",
  "Marsh Warbler",
  "Meadow Pipit",
  "Mediterranean Gull",
  "Common Gull",
  "Mistle Thrush",
  "Middle Spotted Woodpecker",
  "Mute Swan",
  "Hen Harrier",
  "Northern Lapwing",
  "Northern Wheatear",
  "Ortolan Bunting",
  "Pallid Swift",
  "Peregrine Falcon",
  "Purple Heron",
  "Red-breasted Flycatcher",
  "Red-backed Shrike",
  "Red Crossbill",
  "Redwing",
  "Reed Bunting",
  "Red-throated Pipit",
  "Ring Ouzel",
  "Rock Pigeon",
  "Rook",
  "Ruddy Turnstone",
  "Sandwich Tern",
  "Sardinian Warbler",
  "Savi's Warbler",
  "Sedge Warbler",
  "Short-toed Snake-Eagle",
  "Short-toed Treecreeper",
  "Eurasian Skylark",
  "Song Thrush",
  "Spanish Sparrow",
  "Spotted Crake",
  "Spotted Flycatcher",
  "Squacco Heron",
  "European Stonechat",
  "Syrian Woodpecker",
  "Tawny Owl",
  "Tawny Pipit",
  "Thrush Nightingale",
  "Tree Pipit",
  "Tufted Duck",
  "Water Pipit",
  "Water Rail",
  "Western Barn Owl",
  "Western Marsh Harrier",
  "Eurasian Whimbrel",
  "Whinchat",
  "White Stork",
  "White Wagtail",
  "Whooper Swan",
  "Eurasian Wren",
  "Willow Warbler",
  "Wood Lark",
  "Wood Sandpiper",
  "Yellow-legged Gull",
  "Yellowhammer",
  "unknown / not a bird",
};

static const char *const pb_sinif_latin[PB_SINIF_SAYISI] = {
  "Psittacula eupatria",
  "Apus melba",
  "Hirundo rustica",
  "Nycticorax nycticorax",
  "Panurus biarmicus",
  "Pluvialis squatarola",
  "Chroicocephalus ridibundus",
  "Himantopus himantopus",
  "Sylvia atricapilla",
  "Milvus migrans",
  "Phoenicurus ochruros",
  "Luscinia svecica",
  "Cyanistes caeruleus",
  "Hieraaetus pennatus",
  "Fringilla montifringilla",
  "Melanocorypha calandra",
  "Larus cachinnans",
  "Cettia cetti",
  "Emberiza cirlus",
  "Periparus ater",
  "Ficedula albicollis",
  "Buteo buteo",
  "Fringilla coelebs",
  "Phylloscopus collybita",
  "Grus grus",
  "Cuculus canorus",
  "Tringa nebularia",
  "Delichon urbicum",
  "Alcedo atthis",
  "Gallinula chloropus",
  "Luscinia megarhynchos",
  "Aythya ferina",
  "Coturnix coturnix",
  "Corvus corax",
  "Tringa totanus",
  "Phoenicurus phoenicurus",
  "Carpodacus erythrinus",
  "Actitis hypoleucos",
  "Gallinago gallinago",
  "Apus apus",
  "Sterna hirundo",
  "Emberiza calandra",
  "Charadrius hiaticula",
  "Columba palumbus",
  "Galerida cristata",
  "Calidris alpina",
  "Prunella modularis",
  "Iduna pallida",
  "Podiceps nigricollis",
  "Motacilla flava",
  "Merops apiaster",
  "Streptopelia decaocto",
  "Oriolus oriolus",
  "Pluvialis apricaria",
  "Picus viridis",
  "Pernis apivorus",
  "Larus argentatus",
  "Ficedula hypoleuca",
  "Remiz pendulinus",
  "Turdus merula",
  "Fulica atra",
  "Numenius arquata",
  "Carduelis carduelis",
  "Chloris chloris",
  "Falco subbuteo",
  "Corvus monedula",
  "Garrulus glandarius",
  "Falco tinnunculus",
  "Linaria cannabina",
  "Pica pica",
  "Caprimulgus europaeus",
  "Sitta europaea",
  "Haematopus ostralegus",
  "Erithacus rubecula",
  "Otus scops",
  "Serinus serinus",
  "Spinus spinus",
  "Accipiter nisus",
  "Sturnus vulgaris",
  "Acrocephalus scirpaceus",
  "Scolopax rusticola",
  "Jynx torquilla",
  "Streptopelia turtur",
  "Passer montanus",
  "Turdus pilaris",
  "Regulus ignicapilla",
  "Mareca strepera",
  "Spatula querquedula",
  "Sylvia borin",
  "Anas crecca",
  "Regulus regulus",
  "Anser anser",
  "Ardea cinerea",
  "Podiceps cristatus",
  "Botaurus stellaris",
  "Phalacrocorax carbo",
  "Ardea alba",
  "Phoenicopterus roseus",
  "Parus major",
  "Tringa ochropus",
  "Acrocephalus arundinaceus",
  "Dendrocopos major",
  "Motacilla cinerea",
  "Anser albifrons",
  "Picus canus",
  "Coccothraustes coccothraustes",
  "Corvus cornix",
  "Upupa epops",
  "Passer domesticus",
  "Phylloscopus humei",
  "Hippolais icterina",
  "Dryobates minor",
  "Egretta garzetta",
  "Tachybaptus ruficollis",
  "Athene noctua",
  "Sternula albifrons",
  "Asio otus",
  "Aegithalos caudatus",
  "Anas platyrhynchos",
  "Poecile palustris",
  "Acrocephalus palustris",
  "Anthus pratensis",
  "Ichthyaetus melanocephalus",
  "Larus canus",
  "Turdus viscivorus",
  "Dendrocoptes medius",
  "Cygnus olor",
  "Circus cyaneus",
  "Vanellus vanellus",
  "Oenanthe oenanthe",
  "Emberiza hortulana",
  "Apus pallidus",
  "Falco peregrinus",
  "Ardea purpurea",
  "Ficedula parva",
  "Lanius collurio",
  "Loxia curvirostra",
  "Turdus iliacus",
  "Emberiza schoeniclus",
  "Anthus cervinus",
  "Turdus torquatus",
  "Columba livia",
  "Corvus frugilegus",
  "Arenaria interpres",
  "Thalasseus sandvicensis",
  "Curruca melanocephala",
  "Locustella luscinioides",
  "Acrocephalus schoenobaenus",
  "Circaetus gallicus",
  "Certhia brachydactyla",
  "Alauda arvensis",
  "Turdus philomelos",
  "Passer hispaniolensis",
  "Porzana porzana",
  "Muscicapa striata",
  "Ardeola ralloides",
  "Saxicola rubicola",
  "Dendrocopos syriacus",
  "Strix aluco",
  "Anthus campestris",
  "Luscinia luscinia",
  "Anthus trivialis",
  "Aythya fuligula",
  "Anthus spinoletta",
  "Rallus aquaticus",
  "Tyto alba",
  "Circus aeruginosus",
  "Numenius phaeopus",
  "Saxicola rubetra",
  "Ciconia ciconia",
  "Motacilla alba",
  "Cygnus cygnus",
  "Troglodytes troglodytes",
  "Phylloscopus trochilus",
  "Lullula arborea",
  "Tringa glareola",
  "Larus michahellis",
  "Emberiza citrinella",
  "",
};

#endif /* POKEBIRD_SINIFLAR_H */
