/* Uretilmis dosya — tools/sinif_tablosu.py. ELLE DUZENLEMEYIN.
 * Kaynak: data/egitim/siniflar.csv (179 sinif)
 *
 * Sinif 178 = negatif / bilinmiyor.
 * Diziler flash'ta (const), RAM maliyeti sifir.
 */
#ifndef POKEBIRD_SINIFLAR_H
#define POKEBIRD_SINIFLAR_H

#define PB_SINIF_SAYISI 179

static const char *const pb_sinif_kod[PB_SINIF_SAYISI] = {
  "alepar2",
  "alpswi1",
  "barswa",
  "bcnher",
  "bearee1",
  "bkbplo",
  "bkhgul",
  "bkwsti",
  "blackc1",
  "blakit1",
  "blared1",
  "blueth",
  "blutit",
  "booeag1",
  "brambl",
  "callar1",
  "casgul2",
  "cetwar1",
  "cirbun1",
  "coatit2",
  "colfly1",
  "combuz1",
  "comcha",
  "comchi1",
  "comcra",
  "comcuc",
  "comgre",
  "comhom1",
  "comkin1",
  "commoo3",
  "comnig1",
  "compoc",
  "comqua1",
  "comrav",
  "comred1",
  "comred2",
  "comros",
  "comsan",
  "comsni",
  "comswi",
  "comter",
  "corbun1",
  "corplo",
  "cowpig1",
  "crelar1",
  "dunlin",
  "dunnoc1",
  "eaowar1",
  "eargre",
  "eaywag1",
  "eubeat1",
  "eucdov",
  "eugori2",
  "eugplo",
  "eugwoo2",
  "euhbuz1",
  "euhgul1",
  "eupfly1",
  "euptit1",
  "eurbla",
  "eurcoo",
  "eurcur",
  "eurgol",
  "eurgre1",
  "eurhob",
  "eurjac",
  "eurjay1",
  "eurkes",
  "eurlin1",
  "eurmag1",
  "eurnig1",
  "eurnut2",
  "euroys1",
  "eurrob1",
  "eursco1",
  "eurser1",
  "eursis",
  "eurspa1",
  "eursta",
  "eurwar1",
  "eurwoo",
  "eurwry",
  "eutdov",
  "eutspa",
  "fieldf",
  "firecr1",
  "gadwal",
  "gargan",
  "garwar1",
  "gnwtea",
  "goldcr1",
  "gragoo",
  "graher1",
  "grcgre1",
  "grebit1",
  "grecor",
  "greegr",
  "grefla3",
  "gretit1",
  "grnsan",
  "grrwar1",
  "grswoo",
  "grywag",
  "gwfgoo",
  "gyfwoo1",
  "hawfin",
  "hoocro1",
  "hoopoe",
  "houspa",
  "humwar1",
  "ictwar1",
  "leswoo1",
  "litegr",
  "litgre1",
  "litowl1",
  "litter1",
  "loeowl",
  "lottit1",
  "mallar3",
  "martit2",
  "marwar3",
  "meapip1",
  "medgul1",
  "mewgul",
  "misthr1",
  "miswoo1",
  "mutswa",
  "norhar1",
  "norlap",
  "norwhe",
  "ortbun1",
  "palswi3",
  "perfal",
  "purher1",
  "rebfly",
  "rebshr1",
  "redcro",
  "redwin",
  "reebun",
  "retpip",
  "rinouz1",
  "rocpig",
  "rook1",
  "rudtur",
  "santer1",
  "sarwar1",
  "savwar1",
  "sedwar1",
  "shteag1",
  "shttre1",
  "skylar",
  "sonthr1",
  "spaspa1",
  "spocra1",
  "spofly1",
  "squher1",
  "stonec4",
  "syrwoo1",
  "tawowl1",
  "tawpip1",
  "thrnig1",
  "trepip",
  "tufduc",
  "watpip1",
  "watrai1",
  "webowl1",
  "wemhar1",
  "whimbr5",
  "whinch1",
  "whisto1",
  "whiwag",
  "whoswa",
  "winwre4",
  "wlwwar",
  "woolar1",
  "woosan",
  "yelgul1",
  "yellow2",
  "__negatif__",
};

static const char *const pb_sinif_ad[PB_SINIF_SAYISI] = {
  "İskender Papağanı",
  "Ak Karınlı Ebabil",
  "Kır Kırlangıcı",
  "Gece Balıkçılı",
  "Bıyıklı Baştankara",
  "Gümüş Yağmurcun",
  "Karabaş Martı",
  "Uzunbacak",
  "Kara Başlı Ötleğen",
  "Kara Çaylak",
  "Kara Kızılkuyruk",
  "Mavigerdan",
  "Mavi Baştankara",
  "Küçük Kartal",
  "Dağ İspinozu",
  "Boğmaklı Toygar",
  "Hazar Martısı",
  "Kamışbülbülü",
  "Bahçe Çintesi",
  "Çam Baştankarası",
  "Halkalı Sinekkapan",
  "Şahin",
  "İspinoz",
  "Çıvgın",
  "Turna",
  "Guguk",
  "Yeşilbacak",
  "Ev Kırlangıcı",
  "Yalıçapkını",
  "Sutavuğu",
  "Bülbül",
  "Elmabaş Patka",
  "Bıldırcın",
  "Kuzgun",
  "Kızılbacak",
  "Kızılkuyruk",
  "Çütre",
  "Dere Düdükçünü",
  "Suçulluğu",
  "Ebabil",
  "Sumru",
  "Tarla Çintesi",
  "Halkalı Cılıbıt",
  "Tahtalı",
  "Tepeli Toygar",
  "Kara Karınlı Kumkuşu",
  "Dağbülbülü",
  "Ak Mukallit",
  "Kara Boyunlu Batağan",
  "Sarı Kuyruksallayan",
  "Arıkuşu",
  "Kumru",
  "Sarıasma",
  "Altın Yağmurcun",
  "Yeşil Ağaçkakan",
  "Arı Şahini",
  "Kuzey Gümüş Martısı",
  "Kara Sinekkapan",
  "Çulhakuşu",
  "Karatavuk",
  "Sakarmeke",
  "Kervançulluğu",
  "Saka",
  "Florya",
  "Delice Doğan",
  "Küçük Karga",
  "Alakarga",
  "Kerkenez",
  "Ketenkuşu",
  "Saksağan",
  "Çobanaldatan",
  "Sıvacı",
  "Poyrazkuşu",
  "Kızılgerdan",
  "İshakkuşu",
  "Küçük İskete",
  "Kara Başlı İskete",
  "Atmaca",
  "Sığırcık",
  "Saz Kamışçını",
  "Çulluk",
  "Boyunçeviren",
  "Üveyik",
  "Ağaç Serçesi",
  "Tarla Ardıcı",
  "Sürmeli Çalıkuşu",
  "Boz Ördek",
  "Çıkrıkçın",
  "Boz Ötleğen",
  "Çamurcun",
  "Çalıkuşu",
  "Boz Kaz",
  "Gri Balıkçıl",
  "Bahri",
  "Balaban",
  "Karabatak",
  "Büyük Ak Balıkçıl",
  "Flamingo",
  "Büyük Baştankara",
  "Yeşil Düdükçün",
  "Büyük Kamışçın",
  "Orman Alaca Ağaçkakanı",
  "Dağ Kuyruksallayanı",
  "Sakarca",
  "Küçük Yeşil Ağaçkakan",
  "Kocabaş",
  "Leş Kargası",
  "İbibik",
  "Serçe",
  "Ak Kaşlı Çıvgın",
  "Sarı Mukallit",
  "Küçük Ağaçkakan",
  "Küçük Ak Balıkçıl",
  "Küçük Batağan",
  "Kukumav",
  "Küçük Sumru",
  "Kulaklı Orman Baykuşu",
  "Uzun Kuyruklu Baştankara",
  "Yeşilbaş",
  "Kayın Baştankarası",
  "Çalı Kamışçını",
  "Çayır İncirkuşu",
  "Akdeniz Martısı",
  "Küçük Gümüş Martı",
  "Ökse Ardıcı",
  "Ortanca Ağaçkakan",
  "Kuğu",
  "Gökçe Delice",
  "Kızkuşu",
  "Kuyrukkakan",
  "Kirazkuşu",
  "Boz Ebabil",
  "Gökdoğan",
  "Erguvani Balıkçıl",
  "Küçük Sinekkapan",
  "Kızıl Sırtlı Örümcekkuşu",
  "Çaprazgaga",
  "Kızıl Ardıç",
  "Bataklık Çintesi",
  "Kızıl Gerdanlı İncirkuşu",
  "Boğmaklı Ardıç",
  "Kaya Güvercini",
  "Ekin Kargası",
  "Taşçeviren",
  "Kara Gagalı Sumru",
  "Maskeli Ötleğen",
  "Bataklık Kamışçını",
  "Kındıra Kamışçını",
  "Yılan Kartalı",
  "Bahçe Tırmaşıkkuşu",
  "Tarlakuşu",
  "Öter Ardıç",
  "Söğüt Serçesi",
  "Benekli Suyelvesi",
  "Benekli Sinekkapan",
  "Alaca Balıkçıl",
  "Taşkuşu",
  "Alaca Ağaçkakan",
  "Alaca Baykuş",
  "Kır İncirkuşu",
  "Benekli Bülbül",
  "Ağaç İncirkuşu",
  "Tepeli Patka",
  "Dağ İncirkuşu",
  "Sukılavuzu",
  "Peçeli Baykuş",
  "Saz Delicesi",
  "Sürmeli Kervançulluğu",
  "Çayır Taşkuşu",
  "Leylek",
  "Ak Kuyruksallayan",
  "Ötücü Kuğu",
  "Çıtkuşu",
  "Söğütbülbülü",
  "Orman Toygarı",
  "Orman Düdükçünü",
  "Gümüş Martı",
  "Sarı Çinte",
  "negatif / bilinmiyor",
};

#endif /* POKEBIRD_SINIFLAR_H */
