#!/usr/bin/env python3
"""
class_table.py — data/egitim/siniflar.csv -> firmware/src/ai/classes.h

The model produces 179 class indices; the device needs to turn them into
names. The table lives in flash (`const char *const`), not RAM.

Display names are ENGLISH. The training CSV carries the Turkish name for
historical reasons, so the English name is looked up by eBird code in
data/species_istanbul.csv, which is committed. If a code is missing there the
script stops rather than silently falling back, because a silent fallback
would put one Turkish name in the middle of an English list.

Pure stdlib:
    python tools/class_table.py
"""
from __future__ import annotations

import csv
import pathlib
import sys

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import csv_compat  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
INP = csv_compat.resolve(ROOT / "data" / "egitim" / "classes.csv")
SPECIES = ROOT / "data" / "species_istanbul.csv"
OUTPUT = ROOT / "firmware" / "src" / "ai" / "classes.h"

# The sentinel row the dataset builder writes for the negative class.
# "__negatif__" is the legacy spelling; existing data/egitim/ from an earlier
# run still uses it, so both are accepted and the English one is emitted.
NEGATIVE_CODE = "__negative__"
NEGATIVE_CODES = {"__negative__", "__negatif__"}
NEGATIVE_NAME = "unknown / not a bird"


def escape(s: str) -> str:
    """Escape for a C string literal. Non-ASCII stays as UTF-8 bytes: the
    serial terminal reads UTF-8, and the UI fonts (generated by
    tools/generate_fonts.py) carry the accented letters, so they render on
    screen as they are."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def english_names() -> dict[str, str]:
    """eBird code -> English common name, from the committed species list."""
    if not SPECIES.exists():
        sys.exit(f"{SPECIES} is missing")
    with open(SPECIES, encoding="utf-8") as f:
        return {r["ebird_code"]: r["english_name"].strip()
                for r in csv_compat.reader(f)}


def main() -> None:
    if not INP.exists():
        sys.exit(f"{INP} is missing — run tools/build_dataset.py first.")

    eng = english_names()

    # Accept both the current column names and the legacy Turkish ones, so an
    # existing data/egitim/ from an earlier run still works without
    # regenerating the whole 13 GB dataset.
    LEGACY = {"class_index": "sinif", "ebird_code": "ebird_kodu",
              "birdnet_scientific_name": "birdnet_bilimsel_ad"}

    def col(row, name):
        if name in row:
            return row[name]
        return row.get(LEGACY[name], "")

    rows = []
    with open(INP, encoding="utf-8") as f:
        for s in csv_compat.reader(f):
            code = col(s, "ebird_code")
            if code in NEGATIVE_CODES:
                code = NEGATIVE_CODE
                name = NEGATIVE_NAME
            else:
                name = eng.get(code, "")
                if not name:
                    sys.exit(f"no English name for '{code}' in "
                             f"{SPECIES.name} — the class table would end up "
                             f"with a mix of languages.")
            rows.append((int(col(s, "class_index")), code, name,
                         col(s, "birdnet_scientific_name")))
    rows.sort()

    expected = list(range(len(rows)))
    if [s[0] for s in rows] != expected:
        sys.exit("the indices in siniflar.csv are not 0..N-1 — the table "
                 "would be misaligned")

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"""/* GENERATED FILE — tools/class_table.py. DO NOT EDIT BY HAND.
 * Source: data/egitim/siniflar.csv ({len(rows)} classes)
 *
 * Class {len(rows) - 1} = negative / unknown.
 * The arrays live in flash (const), so they cost no RAM.
 */
#ifndef POKEBIRD_CLASSES_H
#define POKEBIRD_CLASSES_H

#define PB_CLASS_COUNT {len(rows)}

static const char *const pb_class_code[PB_CLASS_COUNT] = {{
""")
        for _, code, _name, _lat in rows:
            f.write(f'  "{escape(code)}",\n')
        f.write("};\n\nstatic const char *const pb_class_name[PB_CLASS_COUNT] = {\n")
        for _, _code, name, _lat in rows:
            f.write(f'  "{escape(name)}",\n')
        # Scientific names: the UI shows them under the species name (the
        # italic line in the design). They sit in flash and cost no RAM.
        f.write("};\n\nstatic const char *const pb_class_latin[PB_CLASS_COUNT] = {\n")
        for _, _code, _name, lat in rows:
            f.write(f'  "{escape(lat)}",\n')
        f.write("};\n\n#endif /* POKEBIRD_CLASSES_H */\n")

    print(f"wrote {OUTPUT.relative_to(ROOT)} — {len(rows)} classes")


if __name__ == "__main__":
    main()
